<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Permohonan_model extends CI_Model
{

    private $table = 'tbl_permohonan';
    private $id = 'id';
	private $column_order = array(null, 'id', 'npm', 'kampus','tbl_permohonan.id_anggota', 'nama_anggota', 'email', 'tbl_keperluan.nama_keperluan as keperluan', 'tbl_status.nama_status as status', 'rincian_keperluan', 'gambar', 'tanggal', 'tanggal_akhir', 'no_hp'); //field yang ada di table user
	private $column_search = array('id','npm', 'kampus', 'nama_anggota', 'email', 'gambar'); //field yang diizin untuk pencarian
	private $order = array('id' => 'desc'); // default order

    function __construct()
    {
        parent::__construct();
    }

	private function _get_datatables_query()
	{

		$this->db->join('tbl_keperluan', 'tbl_permohonan.keperluan = tbl_keperluan.id_keperluan');
		$this->db->join('tbl_status', 'tbl_permohonan.status = tbl_status.id_status');
		$this->db->join('tbl_mahasiswa', 'tbl_permohonan.id_anggota = tbl_mahasiswa.id_anggota');
		$this->db->from($this->table);

		$i = 0;

		foreach ($this->column_search as $item) // looping awal
		{
			if ($_POST['search']['value']) // jika datatable mengirimkan pencarian dengan metode POST
			{

				if ($i === 0) // looping awal
				{
					$this->db->group_start();
					$this->db->like($item, $_POST['search']['value']);
				} else {
					$this->db->or_like($item, $_POST['search']['value']);
				}

				if (count($this->column_search) - 1 == $i)
					$this->db->group_end();
			}
			$i++;
		}

		if (isset($_POST['order'])) {
			$this->db->order_by($this->column_order[$_POST['order']['0']['column']], $_POST['order']['0']['dir']);
		} else if (isset($this->order)) {
			$order = $this->order;
			$this->db->order_by(key($order), $order[key($order)]);
		}
	}

	function get_datatables()
	{
		$this->_get_datatables_query();
		if ($_POST['length'] != -1)
			$this->db->limit($_POST['length'], $_POST['start']);
		$query = $this->db->get();
		return $query->result();
	}

	function count_filtered()
	{
		$this->_get_datatables_query();
		$query = $this->db->get();
		return $query->num_rows();
	}

	public function count_all()
	{
		$this->db->from($this->table);
		return $this->db->count_all_results();
	}

    // get all
    function get_all()
    {
        $this->db->select("npm, nama_anggota, kampus, tbl_keperluan.nama_keperluan as keperluan, tanggal, no_hp");
        $this->db->from($this->table);
		$this->db->join('tbl_mahasiswa', 'tbl_permohonan.id_anggota = tbl_mahasiswa.id_anggota');
        $this->db->join('tbl_keperluan', 'tbl_permohonan.keperluan = tbl_keperluan.id_keperluan');
        $this->db->order_by("id", "desc");
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('tbl_status', 'tbl_permohonan.status = tbl_status.id_status');
        $this->db->join('tbl_keperluan', 'tbl_permohonan.keperluan = tbl_keperluan.id_keperluan');
		$this->db->join('tbl_mahasiswa', 'tbl_permohonan.id_anggota = tbl_mahasiswa.id_anggota');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function getMenunggu()
    {
        $this->db->select("COUNT(id) as total");
        $this->db->from("tbl_permohonan");
        $this->db->where('status', 2);
        return $this->db->get()->row()->total;
    }

    function getTerima()
    {
        $this->db->select("COUNT(id) as total");
        $this->db->from("tbl_permohonan");
        $this->db->where('status', 1);
        return $this->db->get()->row()->total;
    }

    function getTolak()
    {
        $this->db->select("COUNT(id) as total");
        $this->db->from("tbl_permohonan");
        $this->db->where('status', 3);
        return $this->db->get()->row()->total;
    }

    function getMahasiswa()
    {
        $this->db->select("COUNT(id) as total");
        $this->db->from("tbl_permohonan");
        return $this->db->get()->row()->total;
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_permohonan_model.php */
/* Location: ./application/models/Tbl_permohonan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-07 06:06:11 */
/* http://harviacode.com */
